name: Evaluate
on:
  pull_request:
  push:
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Evaluate overlay packages
        run: nix-instantiate .ci/get-flake.nix -A checks.x86_64-linux
